// frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HardCodedAuthenticationService } from './../service/hard-coded-authentication.service'
import { BasicAuthenticationService } from '../service/basic-authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username = 'sudeep'
  password = ''
  errorMessage = 'Invalid Credentials'
  invalidLogin = false
  constructor(private router: Router,
    private hardCodedAuthenticationService: HardCodedAuthenticationService,
    private basicAuthenticationService:BasicAuthenticationService
    ) { }

  ngOnInit() {
  }
  handleLogin() {
    // if(this.username=='sudeep' && this.password=='sudeep'){
    if (this.hardCodedAuthenticationService.authenticate(this.username, this.password)) {
      this.invalidLogin = false
      this.router.navigate(['welcome', this.username])
    } else {
      this.invalidLogin = true
    }
  }

  handleBasicAuthenticationLogin() {
    this.basicAuthenticationService.executeAuthenticationService(this.username, this.password).subscribe(
      response => {
        this.invalidLogin = false
        this.router.navigate(['welcome', this.username])
      }, error => {
        this.invalidLogin = true
      }
    )
  }

  executeJWTAuthenticationService(){
        this.basicAuthenticationService.executeJWTAuthenticationService(this.username, this.password).subscribe(
      response => {
        this.invalidLogin = false
        this.router.navigate(['welcome', this.username])
      }, error => {
        this.invalidLogin = true
      }
    )

  }


}

<h1>Login</h1>

<div class="alert alert-warning" *ngIf='invalidLogin'>{{errorMessage}}</div>

<div class="container">

Username:<input type="text"  name="username" [(ngModel)]="username"/>
Password:<input type="password" name="password" [(ngModel)]="password"/>

<button (click)=executeJWTAuthenticationService() class="btn btn-success">Login</button>
</div>

// TodoApp-master/frontend/src/components/toDoApp/LoginComponent.jsx
import React, { Component } from 'react';
import AuthenticationService from './AuthenticationService.js';

class LoginComponent extends Component {

    constructor() {
        super()
        this.state = { username: "", password: "", hasLoginFailed: false, showSuccessMessage: false }
        this.login = this.login.bind(this);
    }

    inputOnchange = (event) => {
        console.log(`target name: ${event.target.name} and value: ${event.target.value}`)
        this.setState({ [event.target.name]: event.target.value })
    }
    login() {
        AuthenticationService.executeJwtAuthenticationService(this.state.username,this.state.password).then(
            response => {
            AuthenticationService.registerSuccessfulLoginForJwt(this.state.username, response.data.token)
            // AuthenticationService.setupAxiosInterceptors(response.data.token)
            this.props.history.push(`/welcome/${this.state.username}`)
            this.setState({ showSuccessMessage: true })
            this.setState({ hasLoginFailed: false })
            }
        ).catch(
            () => {
            this.setState({ showSuccessMessage: false })
            this.setState({ hasLoginFailed: true })
            }
        );


    }

    render() {
        return (
            <div className="loginComponent">
                <h1>Login</h1>
                <div className="container">
                    {this.state.hasLoginFailed && <div className="alert alert-warning">Invalid credentials</div>}
                    {this.state.showSuccessMessage && <div>Login success</div>}
                    UserName: <input type="text" onChange={(event) => this.inputOnchange(event)} name="username" />
                    Password: <input type="password" onChange={(event) => this.inputOnchange(event)} name="password" />
                    <button className="btn btn-success" onClick={this.login}>Login</button>
                </div>
            </div>
        )
    }
}

export default LoginComponent;
