// frontend/src/app/welcome/welcome.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { WelcomeDataService } from '../service/data/welcome-data.service';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit {
  name=''
  welcomeMessage=''

  constructor(private route:ActivatedRoute,
    private service:WelcomeDataService) { }

  ngOnInit() {
    this.name=this.route.snapshot.params['name']
  }

  serviceTest(){
    // console.log("inside serviceTest");
    this.service.testServiceExecution().subscribe(
      response => this.handleSuccessfulResponse(response),
       error => this.handleSuccessfulResponse(error)
    );
  }

  handleSuccessfulResponse(response){
    // console.log("response:",response.message)
    this.welcomeMessage=response.message
  }
  handleErrorResponse(error){
    this.welcomeMessage=error.error.message

  }

}





<div class="container">
<h1> Welcome {{name}}</h1>
  you can manage your todos <a routerLink="/todos"> here</a>

  <br>
  <button (click)="serviceTest()" class="btn btn-success">Test Service </button>
  <br >

  <p *ngIf="welcomeMessage">{{welcomeMessage}}<p>
</div>

// TodoApp-master/frontend/src/components/toDoApp/WelcomeComponent.jsx
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import HelloWorld from '../../api/todo/HelloWorld.js';
class WelcomeComponent extends Component {
    constructor(){
        super()
        this.executeHelloWorldService=this.executeHelloWorldService.bind(this);
        this.state={apiRespose:""}
    }
    executeHelloWorldService(){
        console.log("test1");
        HelloWorld.executeHelloWorldService().then((response)=>{
            this.setState({apiRespose:response.data})
        });

    }
    render() {
        return (
            <>
                <h1>Welcome </h1>
                <div className="container">
                    Welcome {this.props.match.params.name}
                    <Link to="/todos">Todos</Link>
                    <button className="btn btn-success" onClick={this.executeHelloWorldService}>Test Service</button>

                    <span>api response: {this.state.apiRespose}</span>
                </div>
            </>
        );
    }
}
export default WelcomeComponent;
