// TodoApp-master/frontend/src/components/toDoApp/ToDoComponent.jsx
import React, { Component } from 'react';
import * as moment from 'moment';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import TodoDataService from '../../api/todo/TodoDataService.js';
import AuthenticationService from './AuthenticationService.js';
export class ToDoComponent extends Component {
    constructor(props) {
        super(props)
        this.state = {
            id: this.props.match.params.id,
            description: "",
            targetDate: moment(new Date()).format("YYYY-MM-DD")
        }
        this.onSubmit = this.onSubmit.bind(this);
        this.validate = this.validate.bind(this);
    }
    onSubmit(values) {
        console.log("on submit values", values);
        let todoId = this.props.match.params.id;
        let loggedinUserName = AuthenticationService.getLoggedinUser();

        if (todoId === -1) {

            TodoDataService.createTodo(loggedinUserName, { id: this.state.id, description: values.description, targetDate: values.targetDate }).then
                (
                    () => {
                        console.log("create to do:");
                        this.props.history.push("/todos");
                    }
                );

        } else {
            TodoDataService.updateTodo(loggedinUserName, todoId, { id: this.state.id, description: values.description, targetDate: values.targetDate }).then
                (
                    () => {
                        console.log("updated to do:");
                        this.props.history.push("/todos");
                    }
                );

        }



    }
    validate(values) {
        let errors = {}
        if (!values.description) {
            errors.description = 'Please enter a desription'
        }

        if (!moment(values.targetDate).isValid()) {
            errors.targetDate = "Please enter a valid date";
        }
        return errors;
    }
    componentDidMount() {
        let todoId = this.props.match.params.id;

        if (todoId === -1) {
            return
        }
        let loggedinUserName = AuthenticationService.getLoggedinUser();
        TodoDataService.todoByUsernameAndId(loggedinUserName, todoId).then(
            (response) => {
                console.log("response:", response)
                this.setState({ description: response.data.description, targetDate: moment(response.data.targetDate).format("YYYY-MM-DD") })
            }
        )
    }
    render() {
        let description = this.state.description;
        let targetDate = this.state.targetDate;
        return (
            <div>
                <h1>To do</h1>
                <div className="container">
                    <Formik
                        initialValues={{ description, targetDate }}
                        onSubmit={this.onSubmit}
                        validate={this.validate}
                        validateOnBlur={false}
                        validateOnChange={false}
                        enableReinitialize={true}
                    >
                        {
                            (props) => (
                                <Form>
                                    <ErrorMessage name="description" component="div" className="alert alert-warning" />
                                    <fieldset className="form-grooup">
                                        <label>Description</label>
                                        <Field type="text" name="description" className="form-control"></Field>
                                    </fieldset>

                                    <ErrorMessage name="targetDate" component="div" className="alert alert-warning" />
                                    <fieldset className="form-grooup">
                                        <label>Target Date</label>
                                        <Field type="date" name="targetDate" className="form-control"></Field>
                                    </fieldset>
                                    <button className="btn btn-success">Save</button>

                                </Form>
                            )
                        }
                    </Formik>
                </div>
            </div>

        );
    }
}
export default ToDoComponent;

// frontend/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoDataService } from '../service/data/todo-data.service';
import { Todo } from '../list-todos/list-todos.component';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  id: number
  todo: Todo
  constructor(private todoService: TodoDataService,

    private route: ActivatedRoute, private router: Router) { }
  message = ''

  ngOnInit() {
    this.id = this.route.snapshot.params['id']
    this.todo = new Todo(this.id, '', false, new Date())
    if (this.id != -1) {
      this.getTodo()
    }

  }

  getTodo() {
    // this.id = this.route.snapshot.params['id']
    this.todoService.retriveTodo('sudeep', this.id).subscribe(
      response => { this.todo = response }, error => { console.log("error", error) }
    )
  }

  saveTodo() {
    if (this.id === -1) {
      console.log("inside save to do")

      this.todoService.updateTodo('sudeep', this.id, this.todo).subscribe(
        response => {
          this.message = 'to do updated'
          this.router.navigate(['todos'])
        }, error => { }
      )


    } else {
      console.log("inside update to do")

      this.todoService.saveTodo('sudeep', this.todo).subscribe(
        response => { this.router.navigate(['todos']) },
        error => { }
      )
    }
  }

}

<div class="container">
	<h1>Todo</h1>

  <div class="alert alert-success" *ngIf="message">{{message}}</div>

	<fieldset class="form-group">
		<label>description</label>
		<input type="text" [(ngModel)]="todo.description" class="form-control" name="description" required="required" />
</fieldset>

		<fieldset class="form-group">
			<label>targetDate</label>
			<input type="date"
      [ngModel]="todo.targetDate | date :'yyyy-MM-dd'"
      (ngModelChange)="todo.targetDate=$event"


      class="form-control" name="targetDate"  required="required" />
</fieldset>

<button class="btn btn-success" (click)="saveTodo()">Save</button>



</div>
